from .math_teacher import MathTeacher
from .biology_teacher import BiologyTeacher
from .chemistry_teacher import ChemistryTeacher
from .economy_teacher import EconomyTeacher
from .history_teacher import HistoryTeacher
from .languaje_teacher import LanguageTeacher
from .physics_teacher import PhysicsTeacher
from .programming_teacher import ProgrammingTeacher
from .news_agent import NewsAgent
from .planner import Planner